### ISSUE TITLE
Write-up instructions and any supporting change to enable development of openteams-nuxt along with scrud-nuxt

### ISSUE THREAD

**Issue by dcharbon** [openteamsinc/scrud-nuxt#25]
TODO:

- [x] Create structure for the `ScrudComponent` as a Vue library/plugin (`scrud-component` dir in the repo?):
    - [x] `components` dir (`ScrudComponent`, `Form` dir and `Render` dir).
    - [x] `scrud-components.js`
    - [x] `ui-schema.js`
    - [x] Docs describing component's options (`host`, `components` schema map, `url`, `uiType`, `showComponent`, etc.).
- [x] Integrate `scrud-component` package/library to the `scrud-nuxt` example app (use it as a local npm package).
- [x] Add the new package as a dependency/plugin on the `openteams-nuxt` app

**Comment by dalthviz** [comment]
~~Note: Maybe this is related? https://github.com/nuxt/nuxt.js/issues/5816~~
Note: Nuxt Plugins - https://nuxtjs.org/guide/plugins/

**Comment by dalthviz** [comment]
Note: Utility package to scaffold the plugin structure for one vue Single File Component (SFC) or a library of multiple vue SFCs - https://github.com/team-innovation/vue-sfc-rollup
